using System;

namespace NinjaAssemble.Network
{
    [Serializable] public sealed class OwnedHeroDto { public string id; public string characterId; public string heroId; public string displayName; public int level; public long exp; public string frameTier; public bool awakened; public string awakeningId; public string awakeningName; public string currentVariant; public int awakeningLevel; }
    [Serializable] public sealed class BootstrapDto { public OwnedHeroDto[] heroes; public long gold; public long diamond; public int energy; public int energyCap; }
    [Serializable] public sealed class FormationDto { public OwnedHeroDto[] heroes; }
    [Serializable] public sealed class BattleParticipantDto { public string battleUnitId; public string characterId; public string heroId; public bool awakened; public string awakeningId; public string presentationKey; public string displayName; public string variant; public int level; public string side; public int slot; public long maxHp; }
    [Serializable] public sealed class BattleEventDto { public int sequence; public long timestampMs; public string type; public string actorId; public string targetId; public long amount; public bool critical; public string abilityId; public string abilityKind; public string effectKey; public int rageAfter; public string effectType; public string statusId; public long durationMs; public string triggerId; }
    [Serializable] public sealed class BattleResultDto { public long seed; public string rulesetVersion; public string outcome; public long durationMs; public BattleEventDto[] events; }
    [Serializable] public sealed class CampaignItemRewardDto { public string itemId; public string nameEn; public string nameVi; public long quantity; }
    [Serializable] public sealed class CampaignRewardDto { public long playerExp; public long gold; public long diamond; public CampaignItemRewardDto[] items; }
    [Serializable] public sealed class CampaignStageDto { public string stageId; public int chapter; public int stageIndex; public string difficulty; public string nameEn; public string nameVi; public int energyCost; public int minPlayerLevel; public string[] prerequisiteStageIds; public int waveCount; public bool unlocked; public string[] gateMissing; public int clearCount; public int bestStars; public CampaignRewardDto firstClearReward; public CampaignRewardDto repeatReward; }
    [Serializable] public sealed class CampaignStageListDto { public string catalogVersion; public int playerLevel; public int energy; public int energyCap; public CampaignStageDto[] stages; }
    [Serializable] public sealed class CampaignWaveDto { public int waveIndex; public long waveSeed; public BattleParticipantDto[] participants; public BattleResultDto battle; }
    [Serializable] public sealed class CampaignSweepItemDto { public string itemId; public long quantity; }
    [Serializable] public sealed class CampaignSweepDto { public string requestId; public string playerId; public string stageId; public string catalogVersion; public bool replayed; public int energyCost; public int energyAfter; public long playerExpReward; public long goldReward; public long diamondReward; public int accountLevelAfter; public CampaignSweepItemDto[] itemRewards; }
    [Serializable] public sealed class ResourcePveModeDto { public string modeId; public string modeType; public string nameEn; public string nameVi; public int teamSize; public int energyCost; public int dailyAttemptLimit; public int attemptsRemaining; public int minPlayerLevel; public int clearsToday; public long bestScore; public bool playable; public string blockedReason; public long rewardGold; public string rewardItemId; public long rewardItemQuantity; public string resetPolicy; }
    [Serializable] public sealed class ResourcePveBoardDto { public string catalogVersion; public string rulesetVersion; public string gameDate; public int playerLevel; public int energy; public int energyCap; public ResourcePveModeDto[] modes; }
    [Serializable] public sealed class ResourcePveBattleDto { public string requestId; public string playerId; public string modeId; public string catalogVersion; public string rulesetVersion; public string gameDate; public bool replayed; public int energyCost; public int energyAfter; public bool won; public long goldReward; public string itemId; public long itemQuantity; public long seed; public BattleParticipantDto[] participants; public BattleResultDto battle; }
    [Serializable] public sealed class InventoryRewardItemDto { public string itemId; public long quantity; public long balanceAfter; }
    [Serializable] public sealed class InventoryItemDto { public string itemId; public string itemType; public string nameEn; public string nameVi; public long quantity; }
    [Serializable] public sealed class InventoryViewDto { public string catalogVersion; public InventoryItemDto[] items; }

    [Serializable] public sealed class SeasonRewardDto { public string seasonId; public long finalRating; public long rewardAmount; public bool claimable; public bool claimed; }
    [Serializable] public sealed class CompetitiveHistoryItemDto { public string battleId; public string role; public string opponentDisplayName; public string seasonId; public string result; public string winner; public long ratingBefore; public long ratingAfter; public string createdAt; }
    [Serializable] public sealed class ArenaDefenseDto { public string formationId; public OwnedHeroDto[] heroes; }
    [Serializable] public sealed class ShadowDefenseDto { public string seasonId; public OwnedHeroDto[] heroes; }
    [Serializable] public sealed class ArenaOpponentDto { public string playerId; public string displayName; public long rating; public long power; public bool training; }
    [Serializable] public sealed class ArenaStateDto { public string seasonId; public string seasonEndsAt; public long rating; public string ratingProfileVersion; public string rewardProfileVersion; public bool defenseConfigured; public SeasonRewardDto previousSeasonReward; public ArenaOpponentDto[] opponents; }
    [Serializable] public sealed class ArenaBattleDto { public string requestId; public string battleId; public string playerId; public string seasonId; public bool replayed; public bool training; public string opponentPlayerId; public string opponentDisplayName; public long opponentRating; public long opponentPower; public long ratingBefore; public long ratingAfter; public long ratingDelta; public string ratingProfileVersion; public long arenaCoinReward; public string rewardProfileVersion; public string combatStatsVersion; public string abilityProfileVersion; public string techniqueMappingVersion; public string passiveProfileVersion; public BattleParticipantDto[] participants; public BattleResultDto battle; }
    [Serializable] public sealed class ShadowArenaOpponentDto { public string playerId; public string displayName; public long rating; public long totalPower; public bool training; }
    [Serializable] public sealed class ShadowArenaStateDto { public string seasonId; public string seasonEndsAt; public bool eligible; public int ownedCount; public int requiredCount; public int missingCount; public long rating; public string ratingProfileVersion; public string seriesRulesVersion; public string rewardProfileVersion; public bool defenseConfigured; public SeasonRewardDto previousSeasonReward; public ShadowArenaOpponentDto[] opponents; }
    [Serializable] public sealed class ShadowSquadBattleDto { public int squadIndex; public long seed; public bool playerWon; public string tiebreak; public BattleParticipantDto[] participants; public BattleResultDto battle; }
    [Serializable] public sealed class ShadowArenaBattleDto { public string requestId; public string battleId; public string playerId; public string seasonId; public bool replayed; public bool training; public string opponentPlayerId; public long opponentRating; public long opponentPower; public long masterSeed; public string winner; public long ratingBefore; public long ratingAfter; public long ratingDelta; public string ratingProfileVersion; public string seriesRulesVersion; public long shadowCoinReward; public string rewardProfileVersion; public string combatStatsVersion; public string abilityProfileVersion; public string techniqueMappingVersion; public string passiveProfileVersion; public ShadowSquadBattleDto[] squads; }

    [Serializable] public sealed class ShopOfferDto { public string offerId; public string itemId; public string itemNameEn; public string itemNameVi; public long quantity; public string currency; public long price; public int purchaseLimit; public int purchasedCount; public int remaining; public bool purchasable; public string blockedReason; }
    [Serializable] public sealed class ShopEntryDto { public string shopId; public string nameEn; public string nameVi; public string refreshProfile; public ShopOfferDto[] offers; }
    [Serializable] public sealed class ShopViewDto { public string catalogVersion; public string resetKey; public ShopEntryDto[] shops; }
    [Serializable] public sealed class ShopPurchaseResultDto { public string shopId; public string offerId; public string resetKey; public bool replayed; public string currency; public long charged; public long itemBalanceAfter; public int purchaseCount; }
    [Serializable] public sealed class QuestDto { public string questId; public string nameEn; public string nameVi; public string metric; public long target; public long currentValue; public bool claimed; public bool claimable; public long rewardGold; public long rewardDiamond; public string rewardItemId; public long rewardItemQuantity; }
    [Serializable] public sealed class QuestBoardDto { public string catalogVersion; public string resetKey; public string nextResetAt; public QuestDto[] quests; }
    [Serializable] public sealed class QuestClaimDto { public string questId; public string resetKey; public bool replayed; public long gold; public long diamond; public string itemId; public long itemQuantity; public long finalValue; }
    [Serializable] public sealed class MailAttachmentDto { public string kind; public string id; public long quantity; public override string ToString() => $"+{quantity} {id}"; }
    [Serializable] public sealed class MailDto { public string mailId; public string subjectKey; public string subject; public string bodyKey; public string body; public MailAttachmentDto[] attachments; public bool read; public bool claimed; public string createdAt; public string expiresAt; }
    [Serializable] public sealed class MailboxDto { public string mailProfileVersion; public MailDto[] mails; }
    [Serializable] public sealed class MailGrantDto { public string kind; public string id; public long quantity; public long balanceAfter; }
    [Serializable] public sealed class MailClaimDto { public string mailId; public bool replayed; public MailGrantDto[] grants; }
    [Serializable] public sealed class PlayBattleDto { public string battleId; public string stageId; public string campaignCatalogVersion; public string waveRulesVersion; public int energyCost; public int stars; public bool firstClear; public long playerExpReward; public long goldReward; public long diamondReward; public int accountLevelAfter; public InventoryRewardItemDto[] itemRewards; public string combatStatsVersion; public string abilityProfileVersion; public string techniqueMappingVersion; public string passiveProfileVersion; public CampaignWaveDto[] waves; public BattleParticipantDto[] participants; public BattleResultDto battle; }
    [Serializable] public sealed class SummonResultDto { public string heroId; public string characterId; public string displayName; public string rarity; public bool pityTriggered; public bool duplicate; public long duplicateHeroCoins; public int pullsSincePity; public string bannerVersion; public long seed; }
    [Serializable] public sealed class UpgradeResultDto { public OwnedHeroDto hero; public long goldCost; public string costProfileVersion; }
    [Serializable] public sealed class FormationRequestDto { public string[] playerHeroIds; }
    [Serializable] public sealed class ActionRequestDto { public string requestId; }
    [Serializable] public sealed class VariantRequestDto { public string variant; }
}
