package com.ninjaassemble.battle.sim;

/** Timestamped deterministic battle events. */
public enum BattleEventType {
    BATTLE_START,
    ACTION_READY,
    BASIC_ATTACK_START,
    BASIC_ATTACK_HIT,
    BASIC_ATTACK_END,
    CAST_START,
    CAST_COMPLETE,
    ATTACK,
    ABILITY,
    RAGE_GAIN,
    RAGE_FULL,
    RAGE_SKILL_READY,
    RAGE_SKILL_CAST_START,
    RAGE_SKILL_HIT,
    RAGE_SKILL_CAST_END,
    DAMAGE,
    HEAL,
    SHIELD,
    SHIELD_ABSORB,
    STATUS_APPLIED,
    STATUS_TICK,
    STATUS_EXPIRED,
    STATUS_REMOVED,
    STATUS_CLEANSED,
    CLEANSE,
    DISPEL,
    INTERRUPT,
    ACTION_BLOCKED,
    PASSIVE_TRIGGER,
    REVIVE,
    KO,
    BATTLE_END
}
